
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>ShopLookup</AssemblyName>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Remove="Assets\EdgeBlur.fx" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\All.png" />
    <None Remove="Assets\Coins.png" />
    <None Remove="Assets\EdgeBlur.xnb" />
    <None Remove="Assets\NoIcon.png" />
    <None Remove="Assets\QoT.png" />
    <None Remove="Assets\Slot.png" />
    <None Remove="Assets\Vanilla.png" />
    <None Remove="changelog.txt" />
    <None Remove="description_workshop.txt" />
    <None Remove="description_workshop_en.txt" />
    <None Remove="icon_workshop.png" />
    <None Remove="Localization\zh-Hans_Mods.ShopLookup.hjson" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\EdgeBlur.xnb" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RUIModule\RUIModule.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ForOneAdvertisementSystem">
      <HintPath>lib\ForOneAdvertisementSystem.dll</HintPath>
    </Reference>
    <Reference Include="RUIModule">
      <HintPath>lib\RUIModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>